// Auto-generated by LibreLane
module D14_topcell(
`ifdef USE_POWER_PINS
  inout avdd,
  inout avss,
`endif
  input Vin,
  input Vin_neg,
  output vw11,
  output vw42,
  output vpre1,
  output vpre2,
  output vpost1,
  output vpost2
);
endmodule
