/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module layer_input(vdd, vss, Iext1, vout_1, nvout_1, Iext2, vout_2, nvout_2, Iext3, vout_3, nvout_3, vout_4, Iext4, nvout_4);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  input Iext1;
  wire Iext1;
  output vout_1;
  wire vout_1;
  output nvout_1;
  wire nvout_1;
  input Iext2;
  wire Iext2;
  output vout_2;
  wire vout_2;
  output nvout_2;
  wire nvout_2;
  input Iext3;
  wire Iext3;
  output vout_3;
  wire vout_3;
  output nvout_3;
  wire nvout_3;
  output vout_4;
  wire vout_4;
  input Iext4;
  wire Iext4;
  output nvout_4;
  wire nvout_4;
  neurona_lvs x1 (
    .Iin(Iext1),
    .spike(vout_1),
    .spike_neg(nvout_1),
    .vdd(vdd),
    .vss(vss)
  );
  neurona_lvs x2 (
    .Iin(Iext2),
    .spike(vout_2),
    .spike_neg(nvout_2),
    .vdd(vdd),
    .vss(vss)
  );
  neurona_lvs x3 (
    .Iin(Iext3),
    .spike(vout_3),
    .spike_neg(nvout_3),
    .vdd(vdd),
    .vss(vss)
  );
  neurona_lvs x4 (
    .Iin(Iext4),
    .spike(vout_4),
    .spike_neg(nvout_4),
    .vdd(vdd),
    .vss(vss)
  );
endmodule
