/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module stdp_4x2(avdd, avss, A, B, nvpre1, vpre1, vpre2, nvpre2, vpre3, nvpre3, vpre4, nvpre4, vpost1, nvpost1, vpost2, nvpost2, ifwd1, ifwd2, vw11, vw42);
  inout avdd;
  wire avdd;
  inout avss;
  wire avss;
  inout A;
  wire A;
  inout B;
  wire B;
  input nvpre1;
  wire nvpre1;
  input vpre1;
  wire vpre1;
  input vpre2;
  wire vpre2;
  input nvpre2;
  wire nvpre2;
  input vpre3;
  wire vpre3;
  input nvpre3;
  wire nvpre3;
  input vpre4;
  wire vpre4;
  input nvpre4;
  wire nvpre4;
  input vpost1;
  wire vpost1;
  input nvpost1;
  wire nvpost1;
  input vpost2;
  wire vpost2;
  input nvpost2;
  wire nvpost2;
  output ifwd1;
  wire ifwd1;
  output ifwd2;
  wire ifwd2;
  inout vw11;
  wire vw11;
  inout vw42;
  wire vw42;
  wire net1;
  wire net2;
  wire net3;
  wire net4;
  wire net5;
  wire net6;
  wire net7;
  wire net8;
  stdp x1 (
    .Iout(net7),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost1),
    .nvpre(nvpre1),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost1),
    .vpre(vpre1),
    .vw(vw11)
  );
  Current_limit x10 (
    .avdd(avdd),
    .i_SUM(net8),
    .ifwd(ifwd2)
  );
  stdp x2 (
    .Iout(net7),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost1),
    .nvpre(nvpre2),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost1),
    .vpre(vpre2),
    .vw(net3)
  );
  stdp x3 (
    .Iout(net7),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost1),
    .nvpre(nvpre3),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost1),
    .vpre(vpre3),
    .vw(net2)
  );
  stdp x4 (
    .Iout(net7),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost1),
    .nvpre(nvpre4),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost1),
    .vpre(vpre4),
    .vw(net1)
  );
  stdp x5 (
    .Iout(net8),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost2),
    .nvpre(nvpre1),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost2),
    .vpre(vpre1),
    .vw(net4)
  );
  stdp x6 (
    .Iout(net8),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost2),
    .nvpre(nvpre2),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost2),
    .vpre(vpre2),
    .vw(net6)
  );
  stdp x7 (
    .Iout(net8),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost2),
    .nvpre(nvpre3),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost2),
    .vpre(vpre3),
    .vw(net5)
  );
  stdp x8 (
    .Iout(net8),
    .avdd(avdd),
    .avss(avss),
    .nvpost(nvpost2),
    .nvpre(nvpre4),
    .vb_idep(B),
    .vb_itd(A),
    .vb_itp(B),
    .vb_pot(A),
    .vpost(vpost2),
    .vpre(vpre4),
    .vw(vw42)
  );
  Current_limit x9 (
    .avdd(avdd),
    .i_SUM(net7),
    .ifwd(ifwd1)
  );
endmodule
