/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module layer_output(vdd, vss, Iext1, vout_1, nvout_1, Iext2, vout_2, nvout_2);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  input Iext1;
  wire Iext1;
  output vout_1;
  wire vout_1;
  output nvout_1;
  wire nvout_1;
  input Iext2;
  wire Iext2;
  output vout_2;
  wire vout_2;
  output nvout_2;
  wire nvout_2;
  neurona_lvs x1 (
    .Iin(Iext1),
    .spike(vout_1),
    .spike_neg(nvout_1),
    .vdd(vdd),
    .vss(vss)
  );
  neurona_lvs x2 (
    .Iin(Iext2),
    .spike(vout_2),
    .spike_neg(nvout_2),
    .vdd(vdd),
    .vss(vss)
  );
endmodule
